name: netket_env

channels:
  - defaults
  - pytorch 
  - conda-forge

dependencies:
  - python=3.7
  - clang
  - cmake
  - ninja
  - pip
  - scipy
  - numpy
  - matplotlib
  - openmpi
  - mpi4py
  - blas
  - mkl
  - pytorch 
  - torchvision
