name: CI sharding

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test_sharding:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    name: "Tests Sharding"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Pip install packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install jaxlib
          pip install -e ".[dev,extra]"

      - name: run tests on 2 cpus
        run: |
          ./test_sharding/run_test_sharding.sh
